platform :ios, "9.0"
use_frameworks!

def default_pods
    inherit! :search_paths
    
    pod 'ManaKit', :path => '../'
    
    pod 'Sync'
    pod 'FontAwesome.swift'
    pod 'Kanna', '~> 4.0.0'
    pod 'PromiseKit'#, '~> 6.0'
    pod 'SSZipArchive'
    pod 'SDWebImage'#, '~> 4.0'
end

target 'ManaKit_Example' do
    default_pods
end

target 'ManaKit_Tests' do
    default_pods
end
