platform :ios, "10.3"
use_frameworks!

def default_pods
    inherit! :search_paths
    
    pod 'ManaKit', :path => '../'
    
    pod 'FontAwesome.swift'
    pod 'Kanna', '~> 4.0.0'
    pod 'KeychainAccess'
    pod 'MBProgressHUD'
    pod 'PromiseKit'
    pod 'SDWebImage'
    pod 'Sync'
end

target 'ManaKit_Example' do
    default_pods
end

target 'ManaKit_Tests' do
    default_pods
end
